#ifndef FSFUSE_ACTION_H_
#define FSFUSE_ACTION_H_

enum {
    FSFUSE_ACTION_KEY_BEFORE_FIRST,

    FSFUSE_ACTION_KEY_1,
    FSFUSE_ACTION_KEY_2,
    FSFUSE_ACTION_KEY_3,
    FSFUSE_ACTION_KEY_4,
    FSFUSE_ACTION_KEY_5,
    FSFUSE_ACTION_KEY_6,
    FSFUSE_ACTION_KEY_7,
    FSFUSE_ACTION_KEY_8,
    FSFUSE_ACTION_KEY_9,
    FSFUSE_ACTION_KEY_0,

    FSFUSE_ACTION_KEY_Q,
    FSFUSE_ACTION_KEY_W,
    FSFUSE_ACTION_KEY_E,
    FSFUSE_ACTION_KEY_R,
    FSFUSE_ACTION_KEY_T,
    FSFUSE_ACTION_KEY_Y,
    FSFUSE_ACTION_KEY_U,
    FSFUSE_ACTION_KEY_I,
    FSFUSE_ACTION_KEY_O,
    FSFUSE_ACTION_KEY_P,

    FSFUSE_ACTION_KEY_A,
    FSFUSE_ACTION_KEY_S,
    FSFUSE_ACTION_KEY_D,
    FSFUSE_ACTION_KEY_F,
    FSFUSE_ACTION_KEY_G,
    FSFUSE_ACTION_KEY_H,
    FSFUSE_ACTION_KEY_J,
    FSFUSE_ACTION_KEY_K,
    FSFUSE_ACTION_KEY_L,
    FSFUSE_ACTION_KEY_ENTER,

    FSFUSE_ACTION_KEY_CAPSSHIFT,
    FSFUSE_ACTION_KEY_Z,
    FSFUSE_ACTION_KEY_X,
    FSFUSE_ACTION_KEY_C,
    FSFUSE_ACTION_KEY_V,
    FSFUSE_ACTION_KEY_B,
    FSFUSE_ACTION_KEY_N,
    FSFUSE_ACTION_KEY_M,
    FSFUSE_ACTION_KEY_SYMBOLSHIFT,
    FSFUSE_ACTION_KEY_SPACE,

    FSFUSE_ACTION_KEY_UP,
    FSFUSE_ACTION_KEY_DOWN,
    FSFUSE_ACTION_KEY_LEFT,
    FSFUSE_ACTION_KEY_RIGHT,

    FSFUSE_ACTION_KEY_AFTER_LAST,

    FSFUSE_ACTION_JOYSTICK1_UP,
    FSFUSE_ACTION_JOYSTICK1_DOWN,
    FSFUSE_ACTION_JOYSTICK1_LEFT,
    FSFUSE_ACTION_JOYSTICK1_RIGHT,
    FSFUSE_ACTION_JOYSTICK1_FIRE,

    FSFUSE_ACTION_JOYSTICK2_UP,
    FSFUSE_ACTION_JOYSTICK2_DOWN,
    FSFUSE_ACTION_JOYSTICK2_LEFT,
    FSFUSE_ACTION_JOYSTICK2_RIGHT,
    FSFUSE_ACTION_JOYSTICK2_FIRE,

    FSFUSE_ACTION_AFTER_LAST
};

void fsfuse_action_init(void);

#endif  // FSFUSE_ACTION_H_
