#include <stdio.h>

#include "fsemu/src/fsemu-all.h"
#include "fsfuse-action.h"
#include "fsfuse.h"

// static struct {
// } fsfuse_keyboard;

#define ALL 0

static fsemu_input_configure_keyboard_t keyboard_mapping[] = {
    { FSEMU_KEYBOARD_1, ALL, FSFUSE_ACTION_KEY_1 },
    { FSEMU_KEYBOARD_2, ALL, FSFUSE_ACTION_KEY_2 },
    { FSEMU_KEYBOARD_3, ALL, FSFUSE_ACTION_KEY_3 },
    { FSEMU_KEYBOARD_4, ALL, FSFUSE_ACTION_KEY_4 },
    { FSEMU_KEYBOARD_5, ALL, FSFUSE_ACTION_KEY_5 },
    { FSEMU_KEYBOARD_6, ALL, FSFUSE_ACTION_KEY_6 },
    { FSEMU_KEYBOARD_7, ALL, FSFUSE_ACTION_KEY_7 },
    { FSEMU_KEYBOARD_8, ALL, FSFUSE_ACTION_KEY_8 },
    { FSEMU_KEYBOARD_9, ALL, FSFUSE_ACTION_KEY_9 },
    { FSEMU_KEYBOARD_0, ALL, FSFUSE_ACTION_KEY_0 },

    { FSEMU_KEYBOARD_Q, ALL, FSFUSE_ACTION_KEY_Q },
    { FSEMU_KEYBOARD_W, ALL, FSFUSE_ACTION_KEY_W },
    { FSEMU_KEYBOARD_E, ALL, FSFUSE_ACTION_KEY_E },
    { FSEMU_KEYBOARD_R, ALL, FSFUSE_ACTION_KEY_R },
    { FSEMU_KEYBOARD_T, ALL, FSFUSE_ACTION_KEY_T },
    { FSEMU_KEYBOARD_Y, ALL, FSFUSE_ACTION_KEY_Y },
    { FSEMU_KEYBOARD_U, ALL, FSFUSE_ACTION_KEY_U },
    { FSEMU_KEYBOARD_I, ALL, FSFUSE_ACTION_KEY_I },
    { FSEMU_KEYBOARD_O, ALL, FSFUSE_ACTION_KEY_O },
    { FSEMU_KEYBOARD_P, ALL, FSFUSE_ACTION_KEY_P },

    { FSEMU_KEYBOARD_A, ALL, FSFUSE_ACTION_KEY_A },
    { FSEMU_KEYBOARD_S, ALL, FSFUSE_ACTION_KEY_S },
    { FSEMU_KEYBOARD_D, ALL, FSFUSE_ACTION_KEY_D },
    { FSEMU_KEYBOARD_F, ALL, FSFUSE_ACTION_KEY_F },
    { FSEMU_KEYBOARD_G, ALL, FSFUSE_ACTION_KEY_G },
    { FSEMU_KEYBOARD_H, ALL, FSFUSE_ACTION_KEY_H },
    { FSEMU_KEYBOARD_J, ALL, FSFUSE_ACTION_KEY_J },
    { FSEMU_KEYBOARD_K, ALL, FSFUSE_ACTION_KEY_K },
    { FSEMU_KEYBOARD_L, ALL, FSFUSE_ACTION_KEY_L },
    { FSEMU_KEYBOARD_RETURN, ALL, FSFUSE_ACTION_KEY_ENTER },

    { FSEMU_KEYBOARD_Z, ALL, FSFUSE_ACTION_KEY_Z },
    { FSEMU_KEYBOARD_X, ALL, FSFUSE_ACTION_KEY_X },
    { FSEMU_KEYBOARD_C, ALL, FSFUSE_ACTION_KEY_C },
    { FSEMU_KEYBOARD_V, ALL, FSFUSE_ACTION_KEY_V },
    { FSEMU_KEYBOARD_B, ALL, FSFUSE_ACTION_KEY_B },
    { FSEMU_KEYBOARD_N, ALL, FSFUSE_ACTION_KEY_N },
    { FSEMU_KEYBOARD_M, ALL, FSFUSE_ACTION_KEY_M },
    { FSEMU_KEYBOARD_SPACE, ALL, FSFUSE_ACTION_KEY_SPACE },

    { FSEMU_KEYBOARD_LSHIFT, ALL, FSFUSE_ACTION_KEY_CAPSSHIFT },
    { FSEMU_KEYBOARD_RSHIFT, ALL, FSFUSE_ACTION_KEY_CAPSSHIFT },
    { FSEMU_KEYBOARD_LCTRL, ALL, FSFUSE_ACTION_KEY_SYMBOLSHIFT },
    { FSEMU_KEYBOARD_RCTRL, ALL, FSFUSE_ACTION_KEY_SYMBOLSHIFT },

    { FSEMU_KEYBOARD_UP, ALL, FSFUSE_ACTION_KEY_UP },
    { FSEMU_KEYBOARD_DOWN, ALL, FSFUSE_ACTION_KEY_DOWN },
    { FSEMU_KEYBOARD_LEFT, ALL, FSFUSE_ACTION_KEY_LEFT },
    { FSEMU_KEYBOARD_RIGHT, ALL, FSFUSE_ACTION_KEY_RIGHT },

    // { FSEMU_KEYBOARD_F1, ALL, FSFUSE_ACTION_KEY_F1 },
    // { FSEMU_KEYBOARD_ESCAPE, ALL, FSFUSE_ACTION_KEY_ESCAPE },

    { 0, 0, 0 }
};

static fsemu_input_configure_keyboard_t keyboard_shortcuts_mapping[] = {
    // FIXME: Should be FSEMU default?
    { FSEMU_KEYBOARD_F11, 0, FSEMU_ACTION_OSKEYBOARD },
    { 0, 0, 0 },
};
// ----------------------------------------------------------------------------

void fsfuse_keyboard_init(void)
{
    // fsuae_log_debug("[INPUT] fsuae_keyboard_init\n");
    fsemu_input_configure_keyboard(keyboard_mapping);
    fsemu_input_configure_keyboard(keyboard_shortcuts_mapping);
}
