#!/bin/sh
set -e

case "`pwd`" in 
    *fs-fuse-private)
        ../fs-uae-launcher-private/fs-uae-launcher --app=fs-fuse
    ;;
    *)
        ../fs-uae-launcher/fs-uae-launcher --app=fs-fuse
    ;;
esac
