#!/bin/sh
set -e

case "`pwd`" in
    *-private)
        exec ../fs-uae-launcher-private/fs-uae-launcher --app=fs-fuse "$@"
    ;;
    *)
        exec ../fs-uae-launcher/fs-uae-launcher --app=fs-fuse "$@"
    ;;
esac
